Mise en place du docker front
Chrono-care/Front pull request #24
Opened 2024-10-04 14:11 UTC by MorganRvl

2024-10-17 09:40 UTC, NicoPant requested changes
J'aimerais que la structure du répo soit comme avant et que les fichiers docker etc reviennent à la racine du projet front. Merci

2024-10-27 18:05 UTC, MorganRvl commented
J'ai changé la structure comme dit précédemment.

Il faudra faire attention aux deux points suivants concernant la CI-CD:

-Il faut ajouter les tests dans le projet pour que les tests puissent etre valider dans la ci; une fois effectué il faudra remplacer la ligne 54 par la ligne 55 dans le fichier Front/.github/workflows/ci-cd.yml (un commentaire explique la marche à suivre)

-Pour le deployement, j'ai décidé pour le moment de push les images (front et back) sur docker hub afin de pouvoir les pull par la suite pour build le projet global (on pourra en discuter par la suite si cela ne te convient pas mais c'est la meilleure solution que j'ai trouvé pour le moment)

Pour ce faire il faudra créer un compte sur docker hub et mettre ces credentials dans les secrets github (pour qu'ils soient recupérés par la ci):

il faut aller dans Repository> Paramètres > Secrets et variables > Actions > Nouveau secret de dépôt puis ajouter 'DOCKER_USERNAME' et 'DOCKER_PASSWORD' avec les identifiants Docker Hub.

2024-10-31 13:46 UTC, NicoPant requested changes
Il faudra faire un rebase de develop sur ta branch et ensuite ce sera tout bon !

2024-10-31 15:18 UTC, NicoPant approved these changes

2024-10-31 15:20 UTC, NicoPant commented
Apparemment github me dit qu'il y a encore des conflits ? Je peux pas rebase

2024-10-31 16:53 UTC, merged